# Generated by Django 5.0.1 on 2026-01-08 08:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('daily', 'Daily G-Code'), ('weekly', 'Weekly Forecast'), ('monthly', 'Monthly Forecast'), ('retrograde', 'Retrograde'), ('eclipse', 'Eclipse'), ('full_moon', 'Full Moon'), ('new_moon', 'New Moon'), ('educational', 'Educational')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('prompt_template', models.TextField(help_text='Prompt template with {variable} placeholders')),
                ('variables', models.JSONField(blank=True, help_text='Array of variables used in the template', null=True)),
                ('example_output', models.TextField(blank=True, help_text='Example of generated output')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'G-Code Template',
                'verbose_name_plural': 'G-Code Templates',
                'db_table': 'gcode_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('module', models.CharField(help_text='Python module that generated the log', max_length=100)),
                ('function', models.CharField(help_text='Function that generated the log', max_length=100)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GCodeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('birth_date', models.DateField(help_text="User's birth date")),
                ('birth_time', models.TimeField(blank=True, help_text="User's birth time (optional but recommended)", null=True)),
                ('birth_location', models.CharField(help_text='Birth location (City, Country or Lat/Long)', max_length=255)),
                ('birth_lat', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of birth location', max_digits=9, null=True)),
                ('birth_lng', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of birth location', max_digits=9, null=True)),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone", max_length=50)),
                ('bio', models.TextField(blank=True, help_text="User's bio or spiritual journey")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('email_notifications', models.BooleanField(default=True)),
                ('daily_gcode_enabled', models.BooleanField(default=True, help_text='Enable automatic Daily G-Code calculations')),
                ('preferred_tone', models.CharField(choices=[('inspiring', 'Inspiring'), ('practical', 'Practical'), ('poetic', 'Poetic'), ('technical', 'Technical')], default='inspiring', help_text='Preferred tone for AI-generated content', max_length=20)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'G-Code User',
                'verbose_name_plural': 'G-Code Users',
                'db_table': 'gcode_users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_date', models.DateField(help_text='Date of the transit')),
                ('transit_data', models.JSONField(help_text='Current planetary positions')),
                ('aspects_to_natal', models.JSONField(help_text='Aspects between current transits and natal chart')),
                ('g_code_score', models.IntegerField(help_text='Daily G-Code intensity score (1-100)')),
                ('themes', models.JSONField(help_text='Key themes for the day (as array of hashtags)')),
                ('intensity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('intense', 'Intense')], help_text='Intensity level of the day', max_length=20)),
                ('interpretation', models.TextField(help_text="AI-generated interpretation of the day's transits")),
                ('affirmation', models.TextField(help_text='Daily affirmation generated by AI')),
                ('practical_guidance', models.JSONField(help_text='Array of practical guidance tips')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_transits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Transit',
                'verbose_name_plural': 'Daily Transits',
                'db_table': 'daily_transits',
                'ordering': ['-transit_date'],
                'unique_together': {('user', 'transit_date')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('patch_note', 'Spiritual Patch Note'), ('insight', 'Daily Insight'), ('horoscope', 'Horoscope'), ('educational', 'Educational Content'), ('affirmation', 'Affirmation'), ('retrograde', 'Retrograde Alert')], help_text='Type of generated content', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Generated content body')),
                ('hashtags', models.JSONField(blank=True, help_text='Array of hashtags', null=True)),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('blog', 'Blog'), ('email', 'Email Newsletter')], help_text='Target platform', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('posted', 'Posted'), ('scheduled', 'Scheduled'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Scheduled posting time', null=True)),
                ('posted_at', models.DateTimeField(blank=True, help_text='Actual posting time', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_transit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_content', to='api.dailytransit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Content',
                'verbose_name_plural': 'Generated Content',
                'db_table': 'generated_content',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='NatalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_data', models.JSONField(help_text='Complete natal chart data including planetary positions')),
                ('sun_sign', models.CharField(help_text="Sun sign (e.g., 'Aries')", max_length=20)),
                ('moon_sign', models.CharField(help_text='Moon sign', max_length=20)),
                ('ascendant', models.CharField(help_text='Rising sign', max_length=20)),
                ('dominant_elements', models.JSONField(help_text='Element distribution (fire, earth, air, water)')),
                ('key_aspects', models.JSONField(help_text='Major planetary aspects')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='natal_chart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Natal Chart',
                'verbose_name_plural': 'Natal Charts',
                'db_table': 'natal_charts',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text="Type of activity (e.g., 'login', 'view_dashboard', 'generate_content')", max_length=50)),
                ('metadata', models.JSONField(blank=True, help_text='Additional activity data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
