# Generated by Django 5.0.1 on 2026-01-14 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('gcode_trend', 'G-Code Trend'), ('planetary', 'Planetary Positions'), ('element', 'Element Distribution'), ('forecast', 'Weekly Forecast'), ('network', 'Aspects Network')], help_text='Type of chart this annotation belongs to', max_length=50)),
                ('data_point', models.JSONField(help_text="Data point being annotated (e.g., {'date': '2024-01-15', 'value': 75})")),
                ('note', models.TextField(help_text="User's note or insight")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chart Annotation',
                'verbose_name_plural': 'Chart Annotations',
                'db_table': 'chart_annotations',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'chart_type', 'data_point')},
            },
        ),
    ]
